# Project information
site_name: Andre Guerra's Blog
site_url: https://agu3rra.github.io
site_author: Andre Guerra
site_description: >-
  My personal blog.

# Repository
repo_name: GitHub
repo_url: https://github.com/agu3rra/agu3rra.github.io
edit_uri: edit/main/docs

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/agu3rra
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/agu3rra
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/agu3rra

# Extensions
markdown_extensions:
  - abbr
  - pymdownx.magiclink
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  # - git-revision-date-localized

theme:
  name: material
  logo: logo.png
  favicon: logo-white.png
  palette:
    primary: 'white'
    accent: 'grey'

nav:
  - Home: index.md  # put in sequential blog content here
  - About: about.md
  - Blog posts:  # do not put too many categories until you've enough posts
    - Tackling vulnerabilities in open-source software: blog/vulnsOSS/article.md
    - Pragmatic Security Testing: blog/pragmaticST/article.md
    - Python CA issues on HTTPS corporate services: blog/pythonCustomsCAs/article.md
    - Proxying traffic in iOS13: blog/proxyIos13/article.md
    - TLS Handshake: blog/tlsHandshake/article.md
  - Project pages:
    - Volume Calculations for Digital Elevation Models in Python (volpy) : https://agu3rra.github.io/volpy/