name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up python runtime
        uses: actions/setup-python@v3
          with:
            python-version: 3.x

      - name: 
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: | 
          pip install pipenv
          pipenv install
          pipenv run mkdocs gh-deploy --force
